apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
data:
  DATABASE_NAME: {{ .Values.service.db.dbname | b64enc }}
  DATABASE_URL: {{ printf "jdbc:postgresql://%s:%s/%s" .Values.service.db.host .Values.service.db.sport .Values.service.db.dbname | b64enc }}
  DATABASE_SCHEMA: {{ .Values.service.db.dbschema | b64enc }}
  SPRING_DATASOURCE_USERNAME: cm9sZV9mb3Jfc3ByaW5n
  SPRING_DATASOURCE_PASSWORD: MTIz