spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/Warehouse
    username: role_for_spring
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

app:
  scheduling:
    mode: none
    period: 60000 #ms
    priceIncreasePercentage: 10.1
    optimization:
      spring-batch: false
  currency-service:
    stub-enable: false
    host: http://localhost:8081
    methods:
      get-currency: /currencies