server:
  port: 8081
  
spring:
  profiles:
    active: prod
  cache:
    type: caffeine

aws:
  path: ${path}
  accessKeyId: ${accessKeyId}
  secretAccessKey: ${secretAccessKey}
  region: ${region}
  bucketName: ${bucketName}

app:
  kafka:
    enabled: true
    bootstrapAddress: localhost:9091
    groupId: group1

