spring:
  profiles:
    active: ${springProfile:prod}
  cache:
    type: caffeine

management:
  server:
    port: 9090
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,prometheus

app:
  kafka:
    enabled: true
    bootstrapAddress: localhost:9091
    groupId: group1

camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstname: demo
  generic-properties:
    properties:
      enforceHistoryTimeToLive: false
