spring:
  profiles:
    active: ${springProfile:prod}
  cache:
    type: caffeine

management:
  server:
    port: 9090
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,prometheus

app:
  kafka:
    enabled: false
    bootstrapAddress: localhost:9091
    groupId: group1
