spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/Warehouse
    username: role_for_spring
    password: ${PWD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

app:
  scheduling:
    enabled: true
    optimization: true
    period: 60000 #ms
    priceIncreasePercentage: 10.1