---
apiVersion: v1
kind: Service
metadata:
  name: kafka-test
  namespace: kafka-nms
  labels:
    app: kafka
spec:
  type: NodePort
  ports:
    - port: 9094
      name: plaintext
      protocol: TCP
      nodePort: 30100
      targetPort: 9094
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: kafka-nms
spec:
  selector:
    matchLabels:
      app: kafka
  serviceName: "kafka"
  replicas: 1
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: kafka # has to match .spec.selector.matchLabels
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka:2.11-2.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9094
              name: plaintext
          env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://minikube:30100"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:9094"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-service:2181"
            - name: BROKER_ID_COMMAND
              value: "hostname | cut -d'-' -f2"